export const caseStudies = {
  lifestyle: {
    label: "CASE STUDY 01", title: "Lifestyle Creator Instagram Reel Growth",
    heroImage: { src: "/images/portfolio/beauty-editorial.png", alt: "Editorial lifestyle campaign portrait" },
    previewImage: { src: "/images/portfolio/creator-cafe.png", alt: "Lifestyle campaign post preview" },
    objectiveLabel: "OBJECTIVE", objective: "Turn casual lifestyle footage into hook-led Reels with stronger pacing, captions, and a consistent visual identity.",
    platformsLabel: "PLATFORMS", platforms: ["Instagram", "TikTok"],
    stats: [["+184%", "PROFILE VISITS"], ["+42K", "REEL IMPRESSIONS"]],
    account: "chesca.edits", postLabel: "VLOG CUT / REEL READY",
    proof: {
      problem: "Lifestyle footage was visually appealing but lacked immediate hooks, consistent pacing, and a recognizable series identity.",
      strategy: "Build a repeatable Reel format around one-second hooks, personality-led moments, concise captions, and clear visual continuity.",
      deliverables: ["8 edited Instagram Reels", "8 cover designs", "Story cutdowns", "Caption and posting guide"],
      execution: "Selected the strongest opening moments, tightened pauses, added readable captions, standardized covers, and reviewed retention after publishing.",
      measuredResults: [
        { value: "+184%", label: "Profile visits", context: "Compared with the previous 30-day period" },
        { value: "+42K", label: "Reel impressions", context: "Across the campaign content set" },
      ],
      analyticsImage: "/images/analytics/lifestyle-insights.svg",
      analyticsAlt: "Instagram analytics showing profile visit and Reel impression growth",
      analyticsCaption: "30-day Instagram Insights snapshot",
    },
  },
  cafe: {
    label: "CASE STUDY 02", title: "Manila Cafe Opening Campaign",
    heroImage: { src: "/images/portfolio/manila-brunch.png", alt: "Manila cafe brunch campaign" },
    primaryImage: { src: "/images/portfolio/manila-brunch.png", alt: "Manila cafe brunch prepared for social content" },
    secondaryImage: { src: "/images/portfolio/manila-brunch.png", alt: "Close-up frame from the Manila cafe reel" },
    intro: "A warm, story-led vlog and Reel series created for a local cafe opening in the Philippines.",
    challengeLabel: "THE CHALLENGE", challenge: "Build local excitement with behind-the-scenes footage before opening day.",
    editLabel: "THE EDIT", edit: "Raw kitchen clips became a launch vlog, three vertical teasers, and Instagram Stories using natural sound, quick captions, warm color, and personality-led moments.",
    quote: "Baked in the morning. Edited by evening. Shared with the Community.",
    imageLabel: "MANILA CAFE VLOG", stat: "3,400+", statLabel: "LOCAL REEL VIEWS",
    proof: {
      problem: "A new cafe needed local awareness before opening, but only had disconnected kitchen and behind-the-scenes clips.",
      strategy: "Turn preparation footage into a warm opening story that introduced the people, food, and atmosphere before launch day.",
      deliverables: ["1 launch vlog", "3 vertical teasers", "6 Instagram Stories", "Opening-week content schedule"],
      execution: "Grouped clips into a clear narrative, retained natural sound, added location-led captions, and published teasers in a countdown sequence.",
      measuredResults: [
        { value: "3,400+", label: "Local Reel views", context: "Opening campaign reach" },
        { value: "68%", label: "Non-follower reach", context: "Discovery beyond the existing audience" },
      ],
      analyticsImage: "/images/analytics/cafe-insights.svg",
      analyticsAlt: "Instagram analytics showing local cafe Reel views and non-follower reach",
      analyticsCaption: "Opening-week Reel insights snapshot",
    },
  },
  beauty: {
    caseLabel: "CASE STUDY 03",
    heroImage: { src: "/images/portfolio/beauty-editorial.png", alt: "Editorial beauty Reel campaign" },
    rawImage: { src: "/images/portfolio/beauty-editorial.png", alt: "Raw beauty reel portrait" },
    finalImage: { src: "/images/portfolio/beauty-editorial.png", alt: "Color-graded editorial beauty reel portrait" },
    rawLabel: "RAW FOOTAGE", rawPlaceholder: "UNEDITED CLIP", finalLabel: "FINAL CUT", finalPlaceholder: "EDITORIAL REEL",
    label: "THE TRANSFORMATION", title: "From Raw Clip to Polished Reel",
    description: "Uneven lighting and long product demos were reshaped into concise beauty content using tighter cuts, macro details, soft color grading, animated captions, and natural creator-led delivery.",
    editingLabel: "EDITING DIRECTION", editing: "Clean hooks, tactile product shots, subtle sound design, and a warm blush-and-cherry grade.",
    instagramLabel: "INSTAGRAM SYSTEM", instagram: "Matching covers, Story cutdowns, captions, and a repeatable posting rhythm for a cohesive feed.",
    proof: {
      problem: "Long demonstrations and uneven source footage made the beauty content difficult to follow and easy to scroll past.",
      strategy: "Lead with the finished look, compress each demonstration into tactile details, and build a consistent editorial content system.",
      deliverables: ["6 beauty Reels", "Before-and-after cutdowns", "Matching Reel covers", "Caption and Story assets"],
      execution: "Reordered each edit around the reveal, balanced color and exposure, added macro inserts, and used restrained captions and sound design.",
      measuredResults: [
        { value: "+61%", label: "Average watch time", context: "Compared with previous product demos" },
        { value: "4.8x", label: "Saves and shares", context: "Across the editorial Reel series" },
      ],
      analyticsImage: "/images/analytics/beauty-insights.svg",
      analyticsAlt: "Instagram analytics showing beauty Reel watch time and engagement growth",
      analyticsCaption: "Beauty Reel performance snapshot",
    },
  },
} as const;
